package com.payment.exceptionHandler.constraintType;

/**
 * Created with IntelliJ IDEA.
 * User: Jinesh
 * Date: 11/20/14
 * Time: 2:53 PM
 * To change this template use File | Settings | File Templates.
 */
public enum PZTechnicalExceptionEnum
{
    GATEWAY_CONNECTION_TIMEOUT,
    BANK_CONNECTIVITY_ISSUE,
    SSL_HANDSHAKE_ISSUE,
    UNSUPPORTING_ENCOADING_EXCEPTION,
    NOSUCH_ALGO_EXCEPTION ,
    FILE_NOTFOUND_EXCEPTION,
    IOEXCEPTION,
    DATE_PARSING_EXCEPTION,
    NUMBER_FORMAT_EXCEPTION,
    UNKNOWN_HOST_EXCEPTION,
    MALFORMED_URL_EXCEPITON,
    PROTOCOL_EXCEPTION,
    UNSUPPORTED_ENCOADING_EXCEPTION,
    PARSE_CONFIG_EXCEPTION,
    SAXEXCEPTION,
    JSON_EXCEPTION,
    REMOTE_EXCEPTION,
    HTTP_EXCEPTION,
    SERVICE_EXCEPTION,
    AXISFAULT,
    JSON_PARSE_EXCEPTION,
    JSON_MAPPING_EXCEPTION,
    CERTIFICATE_EXCEPTION,
    UNRECOVERABLE_KEY_EXCEPTION,
    KEY_STORE_EXCEPTION,
    KEY_MANAGEMENT_EXCEPTION,
    NULL_POINTER_EXCEPTION,
    MAPPING_CONFIGURATION_NOT_PROVIDED,
    INVOCATION_EXCEPTION,
    SIGANTURE_EXCEPTION,
    INVALID_KEY_EXCEPTION,
    INVALID_KEY_SPEC_EXCEPTION,
    NOSUCH_PADDING_EXCEPTION,
    BAD_PADDING_EXCEPTION,
    ILLEGAL_BLOCK_SIZE_EXCEPTION,
    NOT_ALLOWED_BY_GATEWAY,
    DOCUMENT_EXCEPTION ,
    ACCOUNT_AUTHENTICATION_EXCEPTION,
    DUPLICATE_USER_CREATION_EXCEPTION,
    DOCUMENTATION_SERVER_CREDENTIAL_NOTFOUND,
    DOCUMENTATION_SERVER_CONNECTION_EXCEPTION
    ;

}