package com.directi.pg.core;

import java.util.Hashtable;

/**
 * Created by Trupti on 7/25/2017.
 */
public class CardUsageType
{
    public static Hashtable usageType = new Hashtable();

    static
    {
        usageType.put("AADVANTAGE","PERSONAL");
        usageType.put("ACCOR CO-BRAND","PERSONAL");
        usageType.put("AGRO","PERSONAL");
        usageType.put("AIRMILES PREMIER","PERSONAL");
        usageType.put("ALIMENTACAO","PERSONAL");
        usageType.put("ARGENTINA GRCC","PERSONAL");
        usageType.put("ATM","PERSONAL");
        usageType.put("ATM CARD","PERSONAL");
        usageType.put("AUTO","PERSONAL");
        usageType.put("BASIC","PERSONAL");
        usageType.put("BASICO","PERSONAL");
        usageType.put("BC CARD","PERSONAL");
        usageType.put("BLACK","PERSONAL");
        usageType.put("BLUE","PERSONAL");
        usageType.put("BLUE AIRMILES CASH BACK CARD","PERSONAL");
        usageType.put("BLUE CASH","PERSONAL");
        usageType.put("BLUE CASHBACK","PERSONAL");
        usageType.put("BLUE REVOLVE","PERSONAL");
        usageType.put("BNDES","PERSONAL");
        usageType.put("BUSAN BANK BC CARD","PERSONAL");
        usageType.put("BUSAN BC CARD","PERSONAL");
        usageType.put("BUSAN BC CHECK","PERSONAL");
        usageType.put("CANADIAN CD","PERSONAL");
        usageType.put("CCSG LENDING","PERSONAL");
        usageType.put("CCSG US CONSUMER REVOLVE","PERSONAL");
        usageType.put("CENTURION","PERSONAL");
        usageType.put("CHUFA CARD","PERSONAL");
        usageType.put("CIRRUS","PERSONAL");
        usageType.put("CITI CARDS","PERSONAL");
        usageType.put("CITIBANK CARD","PERSONAL");
        usageType.put("CLASSIC","PERSONAL");
        usageType.put("CLASSIC/GOLD","PERSONAL");
        usageType.put("CLASSIC/PLATINUM","PERSONAL");
        usageType.put("CLASSIC/SIGNATURE","PERSONAL");
        usageType.put("CO-BRAND","PERSONAL");
        usageType.put("COMPRAS","PERSONAL");
        usageType.put("CONSTRUCARD","PERSONAL");
        usageType.put("CONSUMER","PERSONAL");
        usageType.put("CONSUMER CARD","PERSONAL");
        usageType.put("CONSUMER CHARGE","PERSONAL");
        usageType.put("CONSUMER LENDING","PERSONAL");
        usageType.put("CONSUMER LIMITS EXPANSION","PERSONAL");
        usageType.put("CONSUMER REVOLVE","PERSONAL");
        usageType.put("CONSUMER REVOLVE CO-BRAND","PERSONAL");
        usageType.put("CREDIT","PERSONAL");
        usageType.put("CREDIT COEMITIDA","PERSONAL");
        usageType.put("CULTURA","PERSONAL");
        usageType.put("DAEGU BC CARD","PERSONAL");
        usageType.put("DAEGU BC CHECK","PERSONAL");
        usageType.put("DEBIT","PERSONAL");
        usageType.put("DEFERRED DEBIT","PERSONAL");
        usageType.put("DELAYED DEBIT","PERSONAL");
        usageType.put("DELTA REWARDS","PERSONAL");
        usageType.put("DIAMOND","PERSONAL");
        usageType.put("ELECTRIC ORANGE","PERSONAL");
        usageType.put("ELECTRON","PERSONAL");
        usageType.put("ELECTRONIC","PERSONAL");
        usageType.put("ELO MAIS","PERSONAL");
        usageType.put("ENHANCED","PERSONAL");
        usageType.put("EUROPEAN REGULATED INDIVIDUAL PAY","PERSONAL");
        usageType.put("EXPRESSPAY DIRECT LINK","PERSONAL");
        usageType.put("FOOD CARD","PERSONAL");
        usageType.put("GEN CARD NUMBERS","PERSONAL");
        usageType.put("GIFT","PERSONAL");
        usageType.put("GLOBAL PAYMENT","PERSONAL");
        usageType.put("GM CARD","PERSONAL");
        usageType.put("GOLD","PERSONAL");
        usageType.put("GOLD GRCC","PERSONAL");
        usageType.put("GOLD IMMEDIATE DEBIT","PERSONAL");
        usageType.put("GOLD REVOLVE","PERSONAL");
        usageType.put("GOLD/INFINITE/PLATINUM","PERSONAL");
        usageType.put("GOLD/PLATINUM","PERSONAL");
        usageType.put("GOLD/STANDARD","PERSONAL");
        usageType.put("GOLD/STANDARD/PLATINUM","PERSONAL");
        usageType.put("GOLD/TITANIUM","PERSONAL");
        usageType.put("GOLD/TITANIUM/PLATINUM","PERSONAL");
        usageType.put("GOLD/WORLD","PERSONAL");
        usageType.put("GOLD/WORLD ELITE","PERSONAL");
        usageType.put("GPP","PERSONAL");
        usageType.put("GRAFITE","PERSONAL");
        usageType.put("GRCC","PERSONAL");
        usageType.put("GRCC REVOLVING","PERSONAL");
        usageType.put("GRCC BLUE","PERSONAL");
        usageType.put("GRCC GOLD","PERSONAL");
        usageType.put("GRCC GREEN","PERSONAL");
        usageType.put("GRCC LOC","PERSONAL");
        usageType.put("GRCC PLATINUM","PERSONAL");
        usageType.put("GREEN","PERSONAL");
        usageType.put("GREEN GRCC","PERSONAL");
        usageType.put("GREEN/BLUE","PERSONAL");
        usageType.put("GREEN/GOLD","PERSONAL");
        usageType.put("GUANGZHOU CARD","PERSONAL");
        usageType.put("GUANGZHOU CREDIT","PERSONAL");
        usageType.put("GYEONGNAM BC CARD","PERSONAL");
        usageType.put("HAN SKBC CARD","PERSONAL");
        usageType.put("HAN SKBC CHECK","PERSONAL");
        usageType.put("HANA CARD","PERSONAL");
        usageType.put("HEALTH SAVINGS","PERSONAL");
        usageType.put("HYUNDAI CARD","PERSONAL");
        usageType.put("IBK BC CARD","PERSONAL");
        usageType.put("IBK BC CHECK","PERSONAL");
        usageType.put("IBK INDUSTRIAL BANK","PERSONAL");
        usageType.put("ICARD","PERSONAL");
        usageType.put("IKEA CARD","PERSONAL");
        usageType.put("IMMEDIATE DEBIT","PERSONAL");
        usageType.put("INDIVIDUAL","PERSONAL");
        usageType.put("INFINITE","PERSONAL");
        usageType.put("INFINITE PRIVILEGE","PERSONAL");
        usageType.put("INFINITE/PLATINUM","PERSONAL");
        usageType.put("INFINITE/SIGNATURE","PERSONAL");
        usageType.put("INSTANT CARD","PERSONAL");
        usageType.put("INVALID","PERSONAL");
        usageType.put("JEONBUK CARD","PERSONAL");
        usageType.put("KB KOOKMIN CARD","PERSONAL");
        usageType.put("KB NATIONAL BC CARD","PERSONAL");
        usageType.put("LINE OF CREDIT","PERSONAL");
        usageType.put("LOTTE CARD","PERSONAL");
        usageType.put("LOTTE PENTA","PERSONAL");
        usageType.put("LOTTE WEAVER SKY","PERSONAL");
        usageType.put("LOWES CARD","PERSONAL");
        usageType.put("LOYALTY CARD","PERSONAL");
        usageType.put("MAESTRO","PERSONAL");
        usageType.put("MAESTRO PREPAID VOUCHER MEAL AND FOOD CARD","PERSONAL");
        usageType.put("MAESTRO/PREPAID MAESTRO CONSUMER PROMOTION CARD","PERSONAL");
        usageType.put("MASTERMONEY","PERSONAL");
        usageType.put("MULTIPLO","PERSONAL");
        usageType.put("NANQUIM","PERSONAL");
        usageType.put("NEO CARD","PERSONAL");
        usageType.put("NETWORK CARDS","PERSONAL");
        usageType.put("NEW WORLD","PERSONAL");
        usageType.put("NEW WORLD IMMEDIATE DEBIT","PERSONAL");
        usageType.put("NH CARD","PERSONAL");
        usageType.put("NH CHECK CARD","PERSONAL");
        usageType.put("NH NONGHYUP BC CARD","PERSONAL");
        usageType.put("NH NONGHYUP CHECK","PERSONAL");
        usageType.put("NH PLATINUM","PERSONAL");
        usageType.put("ONE CARD","PERSONAL");
        usageType.put("ONE CHECK CARD","PERSONAL");
        usageType.put("OPEN BLUE REVOLVE","PERSONAL");
        usageType.put("OPEN GOLD REVOLVE","PERSONAL");
        usageType.put("OPEN GREEN REVOLVE","PERSONAL");
        usageType.put("OPEN PLATINUM REVOLVE","PERSONAL");
        usageType.put("OPTIMA","PERSONAL");
        usageType.put("OTHER","PERSONAL");
        usageType.put("OUR CARD","PERSONAL");
        usageType.put("OUR CHECK CARD","PERSONAL");
        usageType.put("PAGAMENTO FORNECEDORES","PERSONAL");
        usageType.put("PAYMENT CARD","PERSONAL");
        usageType.put("PAYPASS","PERSONAL");
        usageType.put("PAYPASS CARD","PERSONAL");
        usageType.put("PEONY","PERSONAL");
        usageType.put("PEONY QUASI-CREDIT CARD","PERSONAL");
        usageType.put("PERSONAL","PERSONAL");
        usageType.put("PERSONAL BLUE REVOLVE","PERSONAL");
        usageType.put("PERSONAL GOLD REVOLVE","PERSONAL");
        usageType.put("PERSONAL GREEN PREPAID","PERSONAL");
        usageType.put("PERSONAL GREEN REVOLVE","PERSONAL");
        usageType.put("PERSONAL GREEN/GOLD GRCC","PERSONAL");
        usageType.put("PERSONAL LOAN PRODUCTS","PERSONAL");
        usageType.put("PERSONAL PLATINUM REVOLVE","PERSONAL");
        usageType.put("PERSONAL REVOLVE","PERSONAL");
        usageType.put("PERSONAL/BLUE","PERSONAL");
        usageType.put("PERSONAL/GRCC","PERSONAL");
        usageType.put("PIN ONLY W/O EBT","PERSONAL");
        usageType.put("PLATINUM","PERSONAL");
        usageType.put("PLATINUM CHARGE","PERSONAL");
        usageType.put("PLATINUM IMMEDIATE DEBIT","PERSONAL");
        usageType.put("PLATINUM REWARDS","PERSONAL");
        usageType.put("PLATINUM/GOLD","PERSONAL");
        usageType.put("PLATINUM/GOLD/STANDARD/TITANIUM MASTERCARD/WORLD","PERSONAL");
        usageType.put("PLATINUM/MASTERCARD NEW WORLD","PERSONAL");
        usageType.put("PLATINUM/MASTERCARD WORLD BLACK EDITION","PERSONAL");
        usageType.put("PLATINUM/STANDARD","PERSONAL");
        usageType.put("PLATINUM/TITANIUM","PERSONAL");
        usageType.put("PLATINUM/WORLD","PERSONAL");
        usageType.put("PLATINUM/WORLD ELITE/WORLD","PERSONAL");
        usageType.put("PLATINUM/WORLD/STANDARD","PERSONAL");
        usageType.put("PLATINUM/WORLD/TITANIUM","PERSONAL");
        usageType.put("PLATINUM/WORLD/VIRTUAL","PERSONAL");
        usageType.put("PREMIER","PERSONAL");
        usageType.put("PREMIUM","PERSONAL");
        usageType.put("PREMIUM PLUS","PERSONAL");
        usageType.put("PREPAGO","PERSONAL");
        usageType.put("PREPAID","PERSONAL");
        usageType.put("PREPAID AWARDS","PERSONAL");
        usageType.put("PREPAID CARD","PERSONAL");
        usageType.put("PREPAID CASH","PERSONAL");
        usageType.put("PREPAID ELECTRON","PERSONAL");
        usageType.put("PREPAID GOLD","PERSONAL");
        usageType.put("PREPAID HORIZON CLASSIC","PERSONAL");
        usageType.put("PREPAID PLATINUM","PERSONAL");
        usageType.put("PREPAID PLATINUM TRAVEL","PERSONAL");
        usageType.put("PREPAID PRIVATE LABEL","PERSONAL");
        usageType.put("PREPAID RELOADABLE","PERSONAL");
        usageType.put("PREPAID TRAVEL MONEY","PERSONAL");
        usageType.put("PREPAID V PAY","PERSONAL");
        usageType.put("PREPAID VIRTUAL","PERSONAL");
        usageType.put("PRIORITY PLATINUM","PERSONAL");
        usageType.put("PRIVATE LABEL","PERSONAL");
        usageType.put("PRIVATE LABEL HIPERCARD","PERSONAL");
        usageType.put("PROPRIETARY","PERSONAL");
        usageType.put("PROPRIETARY/STANDARD","PERSONAL");
        usageType.put("Q-CASH","PERSONAL");
        usageType.put("QUANTUM","PERSONAL");
        usageType.put("RELOADABLE PREPAID","PERSONAL");
        usageType.put("REVOLVE","PERSONAL");
        usageType.put("REVOLVE CONSUMER / SBS","PERSONAL");
        usageType.put("REVOLVE-CLASSIC/BLUE","PERSONAL");
        usageType.put("REVOLVE-GOLD","PERSONAL");
        usageType.put("REWARDS","PERSONAL");
        usageType.put("SALUTE","PERSONAL");
        usageType.put("SAMSUNG CARD","PERSONAL");
        usageType.put("SAMSUNG CHECK","PERSONAL");
        usageType.put("SAMSUNG CHECK CARD","PERSONAL");
        usageType.put("SBS","PERSONAL");
        usageType.put("SBS GOLD","PERSONAL");
        usageType.put("SBS GREEN","PERSONAL");
        usageType.put("SC BC CARD","PERSONAL");
        usageType.put("SC BC CHECK","PERSONAL");
        usageType.put("SEARS","PERSONAL");
        usageType.put("SELECT","PERSONAL");
        usageType.put("SHINHAN BC CARD","PERSONAL");
        usageType.put("SHINHAN BC CHECK","PERSONAL");
        usageType.put("SHINHAN CARD","PERSONAL");
        usageType.put("SHINHAN CARD - CHECK","PERSONAL");
        usageType.put("SIGNATURE","PERSONAL");
        usageType.put("SIGNATURE POINTS REWARDS","PERSONAL");
        usageType.put("STANDARD","PERSONAL");
        usageType.put("STANDARD UNEMBOSSED","PERSONAL");
        usageType.put("STANDARD/ENHANCED","PERSONAL");
        usageType.put("STANDARD/GOLD","PERSONAL");
        usageType.put("STANDARD/GOLD/PLATINUM","PERSONAL");
        usageType.put("STANDARD/GOLD/PLATINUM/WORLD","PERSONAL");
        usageType.put("STANDARD/GOLD/TITANIUM","PERSONAL");
        usageType.put("STANDARD/GOLD/WORLD","PERSONAL");
        usageType.put("STANDARD/PLATINUM","PERSONAL");
        usageType.put("STANDARD/PLATINUM/GOLD","PERSONAL");
        usageType.put("STANDARD/PLATINUM/STANDARD UNEMB","PERSONAL");
        usageType.put("STANDARD/PLATINUM/WORLD","PERSONAL");
        usageType.put("STANDARD/PREPAID","PERSONAL");
        usageType.put("STANDARD/REWARDS/WORLD","PERSONAL");
        usageType.put("STANDARD/TITANIUM/PLATINUM","PERSONAL");
        usageType.put("STANDARD/WORLD","PERSONAL");
        usageType.put("STUDENT","PERSONAL");
        usageType.put("SUMIGIN GOLD","PERSONAL");
        usageType.put("TITANIUM","PERSONAL");
        usageType.put("TITANIUM MASTERCARD","PERSONAL");
        usageType.put("TITANIUM MASTERCARD/WORLD/PLATINUM","PERSONAL");
        usageType.put("TITANIUM/GOLD","PERSONAL");
        usageType.put("TITANIUM/STANDARD","PERSONAL");
        usageType.put("TRIUMPH - SBS LIMITS","PERSONAL");
        usageType.put("ULTRA HIGH NET WORTH","PERSONAL");
        usageType.put("V PAY","PERSONAL");
        usageType.put("VIAGEM","PERSONAL");
        usageType.put("VIRTUAL","PERSONAL");
        usageType.put("VOUCHER","PERSONAL");
        usageType.put("VPAY","PERSONAL");
        usageType.put("WORLD","PERSONAL");
        usageType.put("WORLD BLACK","PERSONAL");
        usageType.put("WORLD BLACK EDITION","PERSONAL");
        usageType.put("WORLD CARD","PERSONAL");
        usageType.put("WORLD ELITE","PERSONAL");
        usageType.put("WORLD ELITE/STANDARD","PERSONAL");
        usageType.put("WORLD REWARDS","PERSONAL");
        usageType.put("WORLD SIGNIA","PERSONAL");
        usageType.put("WORLD/GOLD","PERSONAL");
        usageType.put("WORLD/PLATINUM","PERSONAL");
        usageType.put("WORLD/STANDARD/GOLD","PERSONAL");
        usageType.put("WORLD/WORLD ELITE/PLATINUM","PERSONAL");
        usageType.put("AARP","COMMERCIAL");
        usageType.put("B2B","COMMERCIAL");
        usageType.put("BLUE CHARGE","COMMERCIAL");
        usageType.put("BLUE FOR BUSINESS","COMMERCIAL");
        usageType.put("BUSINESS","COMMERCIAL");
        usageType.put("BUSINESS ELITE","COMMERCIAL");
        usageType.put("BUSINESS ENHANCED","COMMERCIAL");
        usageType.put("BUSINESS EXECUTIVE","COMMERCIAL");
        usageType.put("BUSINESS INFINITE","COMMERCIAL");
        usageType.put("BUSINESS PLATINUM","COMMERCIAL");
        usageType.put("BUSINESS SIGNATURE","COMMERCIAL");
        usageType.put("BUSINESS WORLD","COMMERCIAL");
        usageType.put("BUSINESS WORLD ELITE","COMMERCIAL");
        usageType.put("BUSINESS/CLASSIC","COMMERCIAL");
        usageType.put("BUSINESS/STANDARD","COMMERCIAL");
        usageType.put("CANADA CHARGE CARD","COMMERCIAL");
        usageType.put("CANADA CHARGE CARD - GRCC","COMMERCIAL");
        usageType.put("CENTRAL TRAVEL SOLUTIONS AIR","COMMERCIAL");
        usageType.put("CHARGE","COMMERCIAL");
        usageType.put("CHARGE CARD","COMMERCIAL");
        usageType.put("COMMERCIAL","COMMERCIAL");
        usageType.put("COMMERCIAL PAYMENT ACCOUNT","COMMERCIAL");
        usageType.put("COMMERCIAL PAYMENTS ACCOUNT","COMMERCIAL");
        usageType.put("COMPANY","COMMERCIAL");
        usageType.put("COMPANY GOLD","COMMERCIAL");
        usageType.put("COMPANY REVOLVE","COMMERCIAL");
        usageType.put("CORP-GOLD","COMMERCIAL");
        usageType.put("CORPORATE","COMMERCIAL");
        usageType.put("CORPORATE BLACK CHARGE","COMMERCIAL");
        usageType.put("CORPORATE CARD","COMMERCIAL");
        usageType.put("CORPORATE CO- BRAND","COMMERCIAL");
        usageType.put("CORPORATE CO-BRAND CHARGE","COMMERCIAL");
        usageType.put("CORPORATE COBRAND","COMMERCIAL");
        usageType.put("CORPORATE EXECUTIVE","COMMERCIAL");
        usageType.put("CORPORATE FLEET","COMMERCIAL");
        usageType.put("CORPORATE FLEET CARD","COMMERCIAL");
        usageType.put("CORPORATE FLEET GSA","COMMERCIAL");
        usageType.put("CORPORATE GOLD","COMMERCIAL");
        usageType.put("CORPORATE GOLD CHARGE","COMMERCIAL");
        usageType.put("CORPORATE GOLD REVOLVE","COMMERCIAL");
        usageType.put("CORPORATE GREEN CHARGE","COMMERCIAL");
        usageType.put("CORPORATE GREEN CHARGE GE VPAYMENT","COMMERCIAL");
        usageType.put("CORPORATE GREEN CORPORATE GOLD","COMMERCIAL");
        usageType.put("CORPORATE GREEN REVOLVE","COMMERCIAL");
        usageType.put("CORPORATE NETWORK CARD","COMMERCIAL");
        usageType.put("CORPORATE PLATINUM CHARGE","COMMERCIAL");
        usageType.put("CORPORATE PLATINUM REVOLVE","COMMERCIAL");
        usageType.put("CORPORATE PRODUCT","COMMERCIAL");
        usageType.put("CORPORATE PURCHASING","COMMERCIAL");
        usageType.put("CORPORATE SINGLE CURRENCY","COMMERCIAL");
        usageType.put("CORPORATE T & E","COMMERCIAL");
        usageType.put("CORPORATE T&E","COMMERCIAL");
        usageType.put("CORPORATE- COBRAND","COMMERCIAL");
        usageType.put("CORPORATE/BUSINESS","COMMERCIAL");
        usageType.put("CORPORATE/CORPORATE EXECUTIVE/PURCHASING CARD","COMMERCIAL");
        usageType.put("CORPORATE/INFINITE","COMMERCIAL");
        usageType.put("CORPORATIVO","COMMERCIAL");
        usageType.put("DISTRIBUTION","COMMERCIAL");
        usageType.put("ELECTRONIC BUSINESS","COMMERCIAL");
        usageType.put("ELECTRONIC COMMERCIAL","COMMERCIAL");
        usageType.put("EMPRESARIAL","COMMERCIAL");
        usageType.put("EXECUTIVE","COMMERCIAL");
        usageType.put("EXECUTIVE BUSINESS","COMMERCIAL");
        usageType.put("EXECUTIVE COROPRATE","COMMERCIAL");
        usageType.put("EXECUTIVE CORPORATE","COMMERCIAL");
        usageType.put("FLEET","COMMERCIAL");
        usageType.put("FLEET CARD","COMMERCIAL");
        usageType.put("FLEET/BUSINESS","COMMERCIAL");
        usageType.put("FLEET/BUSINESSCARD","COMMERCIAL");
        usageType.put("FSA-INVALID","COMMERCIAL");
        usageType.put("GNS GOLD CHARGE","COMMERCIAL");
        usageType.put("GNS GREEN CHARGE","COMMERCIAL");
        usageType.put("GNS NETWORK CARD","COMMERCIAL");
        usageType.put("GNS PLATINUM CHARGE","COMMERCIAL");
        usageType.put("GNS PREPAID","COMMERCIAL");
        usageType.put("GOLD/CORPORATE","COMMERCIAL");
        usageType.put("GOVERNMENT CORPORATE","COMMERCIAL");
        usageType.put("GOVERNMENT COMMERCIAL","COMMERCIAL");
        usageType.put("GRMS CORPORATE CONTROL","COMMERCIAL");
        usageType.put("GSA","COMMERCIAL");
        usageType.put("GSA CORPORATE T&E","COMMERCIAL");
        usageType.put("GSA PURCHASING","COMMERCIAL");
        usageType.put("GSA PURCHASING WITH FLEET","COMMERCIAL");
        usageType.put("HSA NON SUBSTANTIATED","COMMERCIAL");
        usageType.put("HSA NON SUBSTANTIATED/MASTERCARD PREPAID GENERAL SPEND","COMMERCIAL");
        usageType.put("HSA NON-SUBSTANTIATED","COMMERCIAL");
        usageType.put("HSA SUBSTANTIATED","COMMERCIAL");
        usageType.put("IBK COMPANIES BC","COMMERCIAL");
        usageType.put("LAROC INTERNATIONAL CORPORATE","COMMERCIAL");
        usageType.put("LOTTE CORPORATION","COMMERCIAL");
        usageType.put("MAESTRO SMALL BUSINESS","COMMERCIAL");
        usageType.put("MICRO BUSINESS","COMMERCIAL");
        usageType.put("NATIONAL CUP ENTERPRISE CARD","COMMERCIAL");
        usageType.put("NH CORPORATE CARD","COMMERCIAL");
        usageType.put("ONE COMPANY CHECK","COMMERCIAL");
        usageType.put("ONE CORPORATE CARD","COMMERCIAL");
        usageType.put("OPEN CHARGE","COMMERCIAL");
        usageType.put("OPEN GOLD CHARGE","COMMERCIAL");
        usageType.put("OPEN GREEN CHARGE","COMMERCIAL");
        usageType.put("OPEN LENDING","COMMERCIAL");
        usageType.put("PERSONAL BLACK CHARGE","COMMERCIAL");
        usageType.put("PERSONAL BLUE CHARGE","COMMERCIAL");
        usageType.put("PERSONAL CHARGE","COMMERCIAL");
        usageType.put("PERSONAL GOLD CHARGE","COMMERCIAL");
        usageType.put("PERSONAL GREEN CHARGE","COMMERCIAL");
        usageType.put("PERSONAL PLATINUM CHARGE","COMMERCIAL");
        usageType.put("PREPAID BUSINESS","COMMERCIAL");
        usageType.put("PREPAID CORPORATE","COMMERCIAL");
        usageType.put("PREPAID CORPORATE T&E","COMMERCIAL");
        usageType.put("PREPAID EMPLOYEE INCENTIVE","COMMERCIAL");
        usageType.put("PREPAID FLEX BENEFIT","COMMERCIAL");
        usageType.put("PREPAID FSA","COMMERCIAL");
        usageType.put("PREPAID GOVERNMENT","COMMERCIAL");
        usageType.put("PREPAID HEALTHCARE","COMMERCIAL");
        usageType.put("PREPAID HSA NON-SUBSTANTIATED","COMMERCIAL");
        usageType.put("PREPAID INSURANCE","COMMERCIAL");
        usageType.put("PREPAID PAYROLL","COMMERCIAL");
        usageType.put("PRIVATE LABEL TRADE PROGRAPERSONALM","COMMERCIAL");
        usageType.put("PROFESSIONAL","COMMERCIAL");
        usageType.put("PURCHASING","COMMERCIAL");
        usageType.put("PURCHASING CARD","COMMERCIAL");
        usageType.put("PURCHASING WITH FLEET","COMMERCIAL");
        usageType.put("PURCHASING/CORPORATE","COMMERCIAL");
        usageType.put("SBS CHARGE","COMMERCIAL");
        usageType.put("SBS GOLD CHARGE","COMMERCIAL");
        usageType.put("SHINHAN CARD - CORPORATE","COMMERCIAL");
        usageType.put("SIGNATURE BUSINESS","COMMERCIAL");
        usageType.put("SMALL BUSINESS","COMMERCIAL");
        usageType.put("SMALL BUSINESS CARD","COMMERCIAL");
        usageType.put("SMALL CORPORATE","COMMERCIAL");
        usageType.put("UATP","COMMERCIAL");
        usageType.put("UNITED AIRLINES CORPORATE CARD-RHAPSODY","COMMERCIAL");
        usageType.put("WORLD BUSINESS","COMMERCIAL");
        usageType.put("WORLD ELITE BUSINESS","COMMERCIAL");
        usageType.put("WORLD ELITE CORPORATE","COMMERCIAL");
        usageType.put("WORLD FOR BUSINESS","COMMERCIAL");
        usageType.put("WORLD/CORPORATE","COMMERCIAL");

    }
}
