package com.directi.pg.core;

import java.util.Hashtable;

/**
 * Created by Trupti on 7/25/2017.
 */
public class UsageType
{
    public static Hashtable usageType = new Hashtable();

    static
    {
        usageType.put("BUSINESS CARD","COMMERCIAL");
        usageType.put("BUSINESS","COMMERCIAL");
        usageType.put("EXECUTIVE BUSINESS","COMMERCIAL");
        usageType.put("CORPORATE T&E","COMMERCIAL");
        usageType.put("CORPORATE CARD","COMMERCIAL");
        usageType.put("CORPORATE","COMMERCIAL");
        usageType.put("SMALL CORPORATE","COMMERCIAL");
        usageType.put("CORPORATE PURCHASING","COMMERCIAL");
        usageType.put("CORPORATE T","COMMERCIAL");
        usageType.put("CORPORATE FLEET CARD","COMMERCIAL");
        usageType.put("WORLD FOR BUSINESS","COMMERCIAL");
        usageType.put("SIGNATURE BUSINESS","COMMERCIAL");
        usageType.put("CORPORATION","COMMERCIAL");
        usageType.put("BLUE FOR BUSINESS","COMMERCIAL");
        usageType.put("GOVERNMENT COMMERCIAL CARD","COMMERCIAL");
        usageType.put("CORPORATE GOLD","COMMERCIAL");
        usageType.put("CORPORATE GREEN","COMMERCIAL");
        usageType.put("CORPORATE GOLD Y PLATINUM","COMMERCIAL");
        usageType.put("CORPORATE REVOLVING","COMMERCIAL");
        usageType.put("MICRO-BUSINESS CARD","COMMERCIAL");
        usageType.put("WORLD ELITE FOR BUSINESS","COMMERCIAL");
        usageType.put("GSA CORPORATE T&E","COMMERCIAL");
        usageType.put("BUSINESS GOLD","COMMERCIAL");
        usageType.put("GOLD BUSINESS","COMMERCIAL");
        usageType.put("VISA COMMERCE","COMMERCIAL");
        usageType.put("CORPORATE EXECUTIVE","COMMERCIAL");
        usageType.put("BUSINESS PLATINUM","COMMERCIAL");
        usageType.put("CORPO.CO.S & RANGES","COMMERCIAL");
        usageType.put("COMMERCIAL TRANSPORT EBT","COMMERCIAL");
        usageType.put("CORP. PURCHASING CARD","COMMERCIAL");
        usageType.put("CORP.GREEN D & RANGES","COMMERCIAL");
        usageType.put("COMMERCIAL","COMMERCIAL");
        usageType.put("WORLD SIGNIA IMMEDIATE DEBIT","COMMERCIAL");
        usageType.put("SMALL BUSINESS CARD","COMMERCIAL");
        usageType.put("CORPORATE SILVER","COMMERCIAL");
        usageType.put("SMALL BUSINESS","COMMERCIAL");
        usageType.put("CORPORATE GREEN EBTA","COMMERCIAL");
        usageType.put("SMALL BUSINESS SBS GREEN","COMMERCIAL");
        usageType.put("CORP.GOLD D & RANGES","COMMERCIAL");
        usageType.put("CORP.GREEN S & RANGES","COMMERCIAL");
        usageType.put("CORP. GOLD S & RANGES","COMMERCIAL");
        usageType.put("SMALL CORPORATE CARD","COMMERCIAL");
        usageType.put("SIGNATURE BUSINESS PLATINUM","COMMERCIAL");
        usageType.put("BUSINESS LOAN","COMMERCIAL");
        usageType.put("PREPAID - CORPORATE T&E","COMMERCIAL");
        usageType.put("BUSINESS IMMEDIATE DEBIT","COMMERCIAL");
        usageType.put("STANDARD","PERSONAL");
        usageType.put("PLATINUM","PERSONAL");
        usageType.put("PREPAID","PERSONAL");
        usageType.put("PREMIER","PERSONAL");
        usageType.put("GOLD","PERSONAL");
        usageType.put("ELECTRON","PERSONAL");
        usageType.put("GOLD PREMIUM","PERSONAL");
        usageType.put("REWARDS CARD","PERSONAL");
        usageType.put("PREMIUM CARD","PERSONAL");
        usageType.put("CORE CARD","PERSONAL");
        usageType.put("PURCHASING","PERSONAL");
        usageType.put("PREMIUM PLUS","PERSONAL");
        usageType.put("ATM ONLY","PERSONAL");
        usageType.put("INFINITE","PERSONAL");
        usageType.put("WORLD CARD","PERSONAL");
        usageType.put("GREEN","PERSONAL");
        usageType.put("SIGNATURE","PERSONAL");
        usageType.put("V PAY","PERSONAL");
        usageType.put("GIFT","PERSONAL");
        usageType.put("OTHER","PERSONAL");
        usageType.put("CHECK CARD","PERSONAL");
        usageType.put("BLACK","PERSONAL");
        usageType.put("BLUE AIRMILES CASH BACK CARD","PERSONAL");
        usageType.put("WORLD","PERSONAL");
        usageType.put("PRIVATE LABEL","PERSONAL");
        usageType.put("FLEET CARD","PERSONAL");
        usageType.put("TITANIUM","PERSONAL");
        usageType.put("OPTIMA","PERSONAL");
        usageType.put("CENTURION","PERSONAL");
        usageType.put("CONSUMER CARD","PERSONAL");
        usageType.put("LOWES CARD","PERSONAL");
        usageType.put("IKEA CARD","PERSONAL");
        usageType.put("GOLD CASH BACK CARD","PERSONAL");
        usageType.put("ICARD","PERSONAL");
        usageType.put("PROPRIETARY","PERSONAL");
        usageType.put("INDIVIDUAL","PERSONAL");
        usageType.put("SEARS","PERSONAL");
        usageType.put("NEW WORLD","PERSONAL");
        usageType.put("EMBOSSED","PERSONAL");
        usageType.put("ATM ONLY - CASHLINE CARD","PERSONAL");
        usageType.put("GSA CARD","PERSONAL");
        usageType.put("WORLD EMBOSSED","PERSONAL");
        usageType.put("BLACK CARD","PERSONAL");
        usageType.put("GOLD IMMEDIATE DEBIT","PERSONAL");
        usageType.put("CONSUMER PREMIUM CARD","PERSONAL");
        usageType.put("ELECTRONIC UNEMBOSSED","PERSONAL");
        usageType.put("WORLD ELITE","PERSONAL");
        usageType.put("VISA CASH","PERSONAL");
        usageType.put("UNEMBOSSED","PERSONAL");
        usageType.put("GLOBAL PAYMENT","PERSONAL");
        usageType.put("WORLD DEBIT EMBOSSED","PERSONAL");
        usageType.put("VIRTUAL","PERSONAL");
        usageType.put("AARP","PERSONAL");
        usageType.put("ATM CARD","PERSONAL");
        usageType.put("WORLD BLACK","PERSONAL");
        usageType.put("OUROCARD","PERSONAL");
        usageType.put("QUANTUM","PERSONAL");
        usageType.put("GOLD/PREM","PERSONAL");
        usageType.put("DELAYED DEBIT","PERSONAL");
        usageType.put("PAYPASS","PERSONAL");
        usageType.put("BLUE","PERSONAL");
        usageType.put("SALUTE","PERSONAL");
        usageType.put("PLUS","PERSONAL");
        usageType.put("GOLD & PLATINUM","PERSONAL");
        usageType.put("REVOLVING","PERSONAL");
        usageType.put("MASTERMONEY","PERSONAL");
        usageType.put("CASH REBATE","PERSONAL");
        usageType.put("PLATINUM IMMEDIATE DEBIT","PERSONAL");
        usageType.put("GM CARD","PERSONAL");
        usageType.put("SILVER","PERSONAL");
        usageType.put("TRAVEL MONEY","PERSONAL");
        usageType.put("GSA PURCHASING","PERSONAL");
        usageType.put("NEW WORLD IMMEDIATE DEBIT","PERSONAL");
        usageType.put("REWARDS","PERSONAL");
        usageType.put("CTS LAND CARD","PERSONAL");
        usageType.put("BLUE CASH","PERSONAL");
        usageType.put("HSA NON-SUBSTANTIATED","PERSONAL");
        usageType.put("PREPAID - ELECTRON","PERSONAL");
        usageType.put("PREPAID TRAVEL MONEY","PERSONAL");
        usageType.put("ELECTRONIC","PERSONAL");
        usageType.put("ELECTRIC ORANGE","PERSONAL");
        usageType.put("PLATINUM TRAVEL","PERSONAL");
        usageType.put("IMMEDIATE DEBIT","PERSONAL");
        usageType.put("BUSINESS ELITE","PERSONAL");
        usageType.put("DEBIT","PERSONAL");
        usageType.put("PREMIUM","PERSONAL");
        usageType.put("BONUS","PERSONAL");
        usageType.put("COMPANION","PERSONAL");
        usageType.put("SBS GOLD Y BLUE","PERSONAL");
        usageType.put("PROPRIETARY ATM","PERSONAL");
        usageType.put("PREPAID CASH","PERSONAL");
        usageType.put("T CARD","PERSONAL");
        usageType.put("DORADA","PERSONAL");
        usageType.put("PEONY","PERSONAL");
        usageType.put("TJ PERSONAL","PERSONAL");
        usageType.put("CENTURION SERVICIO","PERSONAL");
        usageType.put("CHARGE CARD","PERSONAL");
        usageType.put("GOLD GRCC YBLUE","PERSONAL");
        usageType.put("BLUE & REVOLVING","PERSONAL");
        usageType.put("AIRMILES PREMIER","PERSONAL");
        usageType.put("CASH BACK","PERSONAL");
        usageType.put("BMI PLUS","PERSONAL");
        usageType.put("VIRGIN ATLANTIC","PERSONAL");
        usageType.put("GOVERNMENT SERVICES LOAN","PERSONAL");
        usageType.put("REBATE","PERSONAL");
        usageType.put("CREDIT","PERSONAL");
        usageType.put("PREPAID - PRIVATE LABEL","PERSONAL");
        usageType.put("PRIVATE","PERSONAL");
        usageType.put("PREPAID - PLATINUM","PERSONAL");
        usageType.put("CLASSIC PREMIUM","PERSONAL");
        usageType.put("DELTA","PERSONAL");
        usageType.put("REWARDS ONLY","PERSONAL");
        usageType.put("EXPRESS","PERSONAL");
        usageType.put("STANDARD UNEMBOSSED","PERSONAL");
        usageType.put("PEONY MONEY LINK","PERSONAL");
        usageType.put("PEONY QUASI-CREDIT CARD","PERSONAL");
        usageType.put("PAYMENT CARD","PERSONAL");


    }
}
