<%--
  Created by IntelliJ IDEA.
  User: PZ
  Date: 8/7/15
  Time: 4:45 PM
  To change this template use File | Settings | File Templates.
--%>
<%--<input type="test" name="countrycode" size="10" readonly>--%>

<select class="form-control" name="country" id="country" onchange="myjunk1();">
  <option value="Select one">Select a Country</option>
  <option value="AFG|093">Afghanistan</option>
  <option value="ALA|358">Aland Islands</option>
  <option value="ALB|355">Albania</option>
  <option value="DZA|231">Algeria</option>
  <option value="ASM|684">American Samoa</option>
  <option value="AND|376">Andorra</option>
  <option value="AGO|244">Angola</option>
  <option value="AIA|001">Anguilla</option>
  <option value="ATA|000">Antarctica</option>
  <option value="ATG|001">Antigua and Barbuda</option>
  <option value="ARG|054">Argentina</option>
  <option value="ARM|374">Armenia</option>
  <option value="ABW|297">Aruba</option>
  <option value="AUS|061">Australia</option>
  <option value="AUT|043">Austria</option>
  <option value="AZE|994">Azerbaijan</option>
  <option value="BHS|001">Bahamas</option>
  <option value="BHR|973">Bahrain</option>
  <option value="BGD|880">Bangladesh</option>
  <option value="BRB|001">Barbados</option>
  <option value="BLR|375">Belarus</option>
  <option value="BEL|032">Belgium</option>
  <option value="BLZ|501">Belize</option>
  <option value="BEN|229">Benin</option>
  <option value="BMU|001">Bermuda</option>
  <option value="BTN|975">Bhutan</option>
  <option value="BOL|591">Bolivia</option>
  <option value="BIH|387">Bosnia and Herzegovina</option>
  <option value="BWA|267">Botswana</option>
  <option value="BVT|000">Bouvet Island</option>
  <option value="BRA|055">Brazil</option>
  <option value="IOT|246">British Indian Ocean Territory</option>
  <option value="VGB|001">British Virgin Islands</option>
  <option value="BRN|673">Brunei</option>
  <option value="BGR|359">Bulgaria</option>
  <option value="BFA|226">Burkina Faso</option>
  <option value="BDI|257">Burundi</option>
  <option value="KHM|855">Cambodia</option>
  <option value="CMR|237">Cameroon</option>
  <option value="CAN|001">Canada</option>
  <option value="CPV|238">Cape Verde</option>
  <option value="CYM|001">Cayman Islands</option>
  <option value="CAF|236">Central African Republic</option>
  <option value="TCD|235">Chad</option>
  <option value="CHL|056">Chile</option>
  <option value="CHN|086">China</option>
  <option value="CXR|061">Christmas Island</option>
  <option value="CCK|061">Cocos (Keeling) Islands</option>
  <option value="COL|057">Colombia</option>
  <option value="COM|269">Comoros</option>
  <option value="COK|682">Cook Islands</option>
  <option value="CRI|506">Costa Rica</option>
  <option value="CIV|225">Cote d"Ivoire</option>
  <option value="HRV|385">Croatia</option>
  <option value="CUB|053">Cuba</option>
  <option value="CYP|357">Cyprus</option>
  <option value="CZE|420">Czech Republic</option>
  <option value="COD|243">Democratic Republic of the Congo</option>
  <option value="DNK|045">Denmark</option>
  <option value="DJI|253">Djibouti</option>
  <option value="DMA|001">Dominica</option>
  <option value="DOM|001">Dominican Republic</option>
  <option value="ECU|593">Ecuador</option>
  <option value="EGY|020">Egypt</option>
  <option value="SLV|503">El Salvador</option>
  <option value="GNQ|240">Equatorial Guinea</option>
  <option value="ERI|291">Eritrea</option>
  <option value="EST|372">Estonia</option>
  <option value="ETH|251">Ethiopia</option>
  <option value="FLK|500">Falkland Islands</option>
  <option value="FRO|298">Faroe Islands</option>
  <option value="FJI|679">Fiji</option>
  <option value="FIN|358">Finland</option>
  <option value="FRA|033">France</option>
  <option value="GUF|594">French Guiana</option>
  <option value="PYF|689">French Polynesia</option>
  <option value="ATF|000">French Southern and Antarctic Lands</option>
  <option value="GAB|241">Gabon</option>
  <option value="GMB|220">Gambia</option>
  <option value="GEO|995">Georgia</option>
  <option value="DEU|049">Germany</option>
  <option value="GHA|233">Ghana</option>
  <option value="GIB|350">Gibraltar</option>
  <option value="GRC|030">Greece</option>
  <option value="GRL|299">Greenland</option>
  <option value="GRD|001">Grenada</option>
  <option value="GLP|590">Guadeloupe</option>
  <option value="GUM|001">Guam</option>
  <option value="GTM|502">Guatemala</option>
  <option value="GGY|000">Guernsey</option>
  <option value="GIN|224">Guinea</option>
  <option value="GNB|245">Guinea-Bissau</option>
  <option value="GUY|592">Guyana</option>
  <option value="HTI|509">Haiti</option>
  <option value="HMD|672">Heard Island & McDonald Islands</option>
  <option value="HND|504">Honduras</option>
  <option value="HKG|852">Hong Kong</option>
  <option value="HUN|036">Hungary</option>
  <option value="ISL|354">Iceland</option>
  <option value="IND|091">India</option>
  <option value="IDN|062">Indonesia</option>
  <option value="IRN|098">Iran</option>
  <option value="IRQ|964">Iraq</option>
  <option value="IRL|353">Ireland</option>
  <option value="ISR|972">Israel</option>
  <option value="ITA|039">Italy</option>
  <option value="JAM|001">Jamaica</option>
  <option value="JPN|081">Japan</option>
  <option value="JEY|044">Jersey</option>
  <option value="JOR|962">Jordan</option>
  <option value="KAZ|007">Kazakhstan</option>
  <option value="KEN|254">Kenya</option>
  <option value="KIR|686">Kiribati</option>
  <option value="KWT|965">Kuwait</option>
  <option value="KGZ|996">Kyrgyzstan</option>
  <option value="LAO|856">Laos</option>
  <option value="LVA|371">Latvia</option>
  <option value="LBN|961">Lebanon</option>
  <option value="LSO|266">Lesotho</option>
  <option value="LBR|231">Liberia</option>
  <option value="LBY|218">Libya</option>
  <option value="LIE|423">Liechtenstein</option>
  <option value="LTU|370">Lithuania</option>
  <option value="LUX|352">Luxembourg</option>
  <option value="MAC|853">Macau, China</option>
  <option value="MKD|389">Macedonia</option>
  <option value="MDG|261">Madagascar</option>
  <option value="MWI|265">Malawi</option>
  <option value="MYS|060">Malaysia</option>
  <option value="MDV|960">Maldives</option>
  <option value="MLI|223">Mali</option>
  <option value="MLT|356">Malta</option>
  <option value="MHL|692">Marshall Islands</option>
  <option value="MTQ|596">Martinique</option>
  <option value="MRT|222">Mauritania</option>
  <option value="MUS|230">Mauritius</option>
  <option value="MYT|269">Mayotte</option>
  <option value="MEX|052">Mexico</option>
  <option value="FSM|691">Micronesia, Federated States of</option>
    <option value="MDA|373">Moldova</option>
  <option value="MCO|377">Monaco</option>
  <option value="MNG|976">Mongolia</option>
  <option value="MNE|382">Montenegro</option>
  <option value="MSR|001">Montserrat</option>
  <option value="MAR|212">Morocco</option>
  <option value="MOZ|258">Mozambique</option>
  <option value="MMR|095">Myanmar</option>
  <option value="NAM|264">Namibia</option>
  <option value="NRU|674">Nauru</option>
  <option value="NPL|977">Nepal</option>
  <option value="ANT|599">Netherlands Antilles</option>
  <option value="NLD|031">Netherlands</option>
  <option value="NCL|687">New Caledonia</option>
  <option value="NZL|064">New Zealand</option>
  <option value="NIC|505">Nicaragua</option>
  <option value="NER|227">Niger</option>
  <option value="NGA|234">Nigeria</option>
  <option value="NIU|683">Niue</option>
  <option value="NFK|672">Norfolk Island</option>
  <option value="PRK|850">North Korea</option>
  <option value="MNP|001">Northern Mariana Islands</option>
  <option value="NOR|047">Norway</option>
  <option value="OMN|968">Oman</option>
  <option value="PAK|092">Pakistan</option>
  <option value="PLW|680">Palau</option>
  <option value="PSE|970">Palestinian Authority</option>
  <option value="PAN|507">Panama</option>
  <option value="PNG|675">Papua New Guinea</option>
  <option value="PRY|595">Paraguay</option>
  <option value="PER|051">Peru</option>
  <option value="PHL|063">Philippines</option>
  <option value="PCN|064">Pitcairn Islands</option>
  <option value="POL|048">Poland</option>
  <option value="PRT|351">Portugal</option>
  <option value="PRI|001">Puerto Rico</option>
  <option value="QAT|974">Qatar</option>
  <option value="COD|242">Republic of the Congo</option>
  <option value="REU|262">Reunion</option>
  <option value="ROU|040">Romania</option>
  <option value="RUS|007">Russia</option>
  <option value="RWA|250">Rwanda</option>
  <option value="BLM|590">Saint Barthelemy</option>
  <option value="SHN|290">Saint Helena, Ascension & Tristan daCunha</option>
  <option value="KNA|001">Saint Kitts and Nevis</option>
  <option value="LCA|001">Saint Lucia</option>
  <option value="MAF|590">Saint Martin</option>
  <option value="SPM|508">Saint Pierre and Miquelon</option>
  <option value="VCT|001">Saint Vincent and Grenadines</option>
  <option value="WSM|685">Samoa</option>
  <option value="SMR|378">San Marino</option>
  <option value="STP|239">Sao Tome and Principe</option>
  <option value="SAU|966">Saudi Arabia</option>
  <option value="SEN|221">Senegal</option>
  <option value="SRB|381">Serbia</option>
  <option value="SYC|248">Seychelles</option>
  <option value="SLE|232">Sierra Leone</option>
  <option value="SGP|065">Singapore</option>
  <option value="SVK|421">Slovakia</option>
  <option value="SVN|386">Slovenia</option>
  <option value="SLB|677">Solomon Islands</option>
  <option value="SOM|252">Somalia</option>
  <option value="ZAF|027">South Africa</option>
  <option value="SGS|000">South Georgia & South Sandwich Islands</option>
  <option value="KOR|082">South Korea</option>
  <option value="ESP|034">Spain</option>
  <option value="LKA|094">Sri Lanka</option>
  <option value="SDN|249">Sudan</option>
  <option value="SUR|597">Suriname</option>
  <option value="SJM|047">Svalbard and Jan Mayen</option>
  <option value="SWZ|268">Swaziland</option>
  <option value="SWE|046">Sweden</option>
  <option value="CHE|041">Switzerland</option>
  <option value="SYR|963">Syria</option>
  <option value="TWN|886">Taiwan</option>
  <option value="TJK|992">Tajikistan</option>
  <option value="TZA|255">Tanzania</option>
  <option value="THA|066">Thailand</option>
  <option value="TLS|670">Timor-Leste</option>
  <option value="TLS|228">Togo</option>
  <option value="TKL|690">Tokelau</option>
  <option value="TON|676">Tonga</option>
  <option value="TTO|001">Trinidad and Tobago</option>
  <option value="TUN|216">Tunisia</option>
  <option value="TUR|090">Turkey</option>
  <option value="TKM|993">Turkmenistan</option>
  <option value="TCA|001">Turks and Caicos Islands</option>
  <option value="TUV|688">Tuvalu</option>
  <option value="UGA|256">Uganda</option>
  <option value="UKR|380">Ukraine</option>
  <option value="ARE|971">United Arab Emirates</option>
  <option value="GBR|044">United Kingdom</option>
  <option value="USA|001">United States</option>
  <option value="VIR|001">United States Virgin Islands</option>
  <option value="URY|598">Uruguay</option>
  <option value="UZB|998">Uzbekistan</option>
  <option value="VUT|678">Vanuatu</option>
  <option value="VAT|379">Vatican City</option>
  <option value="VEN|058">Venezuela</option>
  <option value="VNM|084">Vietnam</option>
  <option value="WLF|681">Wallis and Futuna</option>
  <option value="ESH|212">Western Sahara</option>
  <option value="YEM|967">Yemen</option>
  <option value="ZMB|260">Zambia</option>
  <option value="ZWE|263">Zimbabwe</option>
</select>