package com.payment.Mail;

/**
 * Created with IntelliJ IDEA.
 * User: Nishant
 * Date: 3/6/14
 * Time: 1:17 PM
 * To change this template use File | Settings | File Templates.
 */
public enum MailPlaceHolder
{
    //common place holders
    LOGO("LOGO"),
    NAME("NAME"),
    COMPANYNAME("COMPANYNAME"),
    SUPPORTLINK("SUPPORTLINK"),
    INVOICENO("INVOICENO"),
    TRACKINGID("TRACKINGID"),
    ORDERDESCRIPTION("ORDERDESCRIPTION"),
    AMOUNT("AMOUNT"),
    CURRENCY("CURRENCY"),
    ORDERID("ORDERID"),
    PAYMENTTERMS("PAYMENTTERMS"),
    CBAMOUNT("CBAMOUNT"),
    RFAMOUNT("RFAMOUNT"),
    REASON("REASON"),
    TERMINALID("TERMINALID"),
    TERMINALDETAILS("TERMINALDETAILS"),
    USERID("USERID"),
    PARTNERNAME("PARTNERNAME"),
    DISPLAYTR("DISPLAYTR"),

    CUSTOMEREMAIL("CUSTOMEREMAIL"),
    TOID("TOID"),
    PASSWORD("PASSWORD"),
    USERNAME("USERNAME"),
    DATE("DATE"),
    MSG("MSG"),
    MSG1("MSG1"),
    MERCHANTCOMPANYNAME("MERCHANTCOMPANYNAME"),

    LIVEURL("LIVEURL"),
    INTEGRATIONURL("INTEGRATIONURL"),
    MCOMNAME("MCOMNAME"),
    DISPLAYNAME("DISPLAYNAME"),
    CARDHOLDERNAME("CARDHOLDERNAME"),

    STATUS("STATUS"),
    DESC("DESC"),
    ORGENIZATIONNAME("ORGENIZATION"),
    PARTNERORGNAME("PARTNERORGNAME"),
    ADMINEMAIL("ADMINEMAIL"),
    SUPPORTEMAIL("SUPPORTEMAIL"),
    COMPANYSUPPORTMAIL("COMPANYSUPPORTMAIL"),
    BILLINGEMAIL("BILLINGEEMAIL"),
    TECHEMAIL("TECHEMAIL"),
    COMPANYFROMADDRESS("COMPANYFROMADDRESS"),
    IPADDRESS("IPADDRESS"),
    SUPPORTURL("SUPPORTURL"),
    SUPPORTMAILFORCUSTOMER("SUPPORTMAILFORCUSTOMER"),
    CONTECTEMAIL("CONTECTEMAIL"),

    AdminEmail("AdminEmail"),
    PartnerEmail("PartnerEmail"),
    MerchantEmail("MerchantEmail"),
    CustomerEmail("CustomerEmail"),
    FraudSystemEmail("FraudSystemEmail"),

    EmailFormAddress("EmailFormAddress"),
    EmailToAddress("EmailToAddress"),
    SUBJECT("SUBJECT"),
    CTOKEN("CTOKEN"),
    PARTNERID("PARTNERID"),
    QUESTION("QUESTION"),
    ANSWER("ANSWER"),

    FROMDATE("FROMDATE"),
    TODATE("TODATE"),
    ACCOUNTID("ACCOUNTID"),

    CAPTUREAMOUNT("CAPTUREAMOUNT"),
    SHIPPINGSITE("SHIPPINGSITE"),
    SHIPPINGID("SHIPPINGID"),
    REMARK("REMARK"),
    M_HOST("M_HOST"),
    M_PORT("M_PORT"),
    M_USERNAME("M_USERNAME"),
    M_PASSWORD("M_PASSWORD"),
    MULTIPALTRANSACTION("MULTIPALTRANSACTION"),
    RELAY_WITH_AUTH("RELAY_WITH_AUTH"),
    HOST_URL("HOST_URL"),
    PROTOCOL("PROTOCOL"),
    SUPPORT_EMAIL_FOR_TRANSACTION_MAIL("SUPPORT_EMAIL_FOR_TRANSACTION_MAIL"),

    //Exception Handel
    CLASS_NAME("CLASS_NAME"),
    METHOD_NAME("METHOD_NAME"),
    MODULE_NAME("MODULE_NAME"),
    OPERATION("OPERATION"),
    MESSAGE("MESSAGE"),
    EXCEPTION_MESSAGE("EXCEPTION_MESSAGE"),
    EXCEPTION_CAUSE("EXCEPTION_CAUSE"),
    EXCEPTION("EXCEPTION"),
    FRAUDMAILID("FRAUDMAILID"),

    //Rejected Transaction
    ERROR_NAME("ERROR_NAME"),
    ERROR_TYPE("ERROR_TYPE"),

    //for fraudRuleChangeIntimation
    FRAUDACCOUNTID("FRAUDACCOUNTID"),

    //Regarding mail with attachment functionality
    ATTACHMENTFILEPATH("ATTACHMENTFILEPATH"),
    ATTACHMENTFILENAME("ATTACHMENTFILENAME"),

    //Added for SMS
    SMS_TO_TELNOCC("SMS_TO_TELNOCC"),
    SMS_TO_TELNO("SMS_TO_TELNO"),
    SMS_FROM_ADDRESS("SMS_FROM_ADDRESS"),
    SMS_HOST("SMS_HOST"),
    SMS_PORT("SMS_PORT"),
    SMS_URL("SMS_URL"),
    SMS_SERVICE("SMS_SERVICE"),

    SMS_USERNAME("SMS_USERNAME"),
    SMS_PASSWORD("SMS_PASSWORD"),
    SMS_FROM_NUMBER("SMS_FROM_NUMBER"),

    PGTYPEID("PGTYPEID"),
    APPLICATION_ID("APPLICATION_ID"),
    URL("URL"),
    GATEWAY_NAME("GATEWAY_NAME"),
    TRANS_STATUS("TRANS_STATUS"),
    TRANS_COUNT("TRANS_COUNT"),
    ATTACHMENTLIST("ATTACHMENTLIST"),
    INVOICE_PRODUCTS("INVOICE_PRODUCTS"),
    INVOICE_URL("INVOICE_URL"),
    LATE_FEE("LATE_FEE"),
    DUE_DATE("DUE_DATE"),

    FROM_TYPE("FROM_TYPE"),
    PARTNER_URL("PARTNER_URL"),


    MSG2("MSG2"),
    PROXYSCHEME("PROXYSCHEME"),
    OTP("OTP"),
    CC("CC"),
    BCC("BCC"),

    DEFAULTTHEME("DEFAULTTHEME"),
    CURRENTTHEME("CURRENTTHEME"),
    FIRSTCOLOR("FIRSTCOLOR"),
    TEMP_LANG("TEMP_LANG"),
    LANG_FOR_INVOICE("LANG_FOR_INVOICE"),
    LINE1("LINE1"),
    GST("GST"),
    TAXAMOUNT("TAXAMOUNT"),
    DUEDATE("DUEDATE"),
    LATEFEE("LATEFEE"),
    AFTEREXPAMOUNT("AFTEREXPAMOUNT"),
    TOTALAMOUNT("TOTALAMOUNT");

    private String placeHolderName;

    MailPlaceHolder (String  placeHolderName)
    {
        this.placeHolderName=placeHolderName;
    }
    public String toString()
    {
        return placeHolderName;
    }
}