CREATE TABLE `product_unit` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `memberid` VARCHAR(20) DEFAULT NULL,
  `unit` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1


CREATE TABLE `default_productlist` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `memberid` VARCHAR(20) NOT NULL,
  `productdesc` VARCHAR(100) DEFAULT NULL,
  `productamount` VARCHAR(20) DEFAULT NULL,
  `unit` VARCHAR(100) DEFAULT NULL,
  `tax` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1