/**
 * MerchantSoap.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.payment.alliedwalled.core.message.com._381808.service;

public interface MerchantSoap extends java.rmi.Remote {
    public com.payment.alliedwalled.core.message.com._381808.service.FailedTransaction[] batchShipping(com.payment.alliedwalled.core.message.com._381808.service.ShippingDetails[] details) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse repeatTransaction(java.lang.String merchantID, java.lang.String transactionID, java.math.BigDecimal amount, java.lang.String currencyID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse refund(java.lang.String merchantID, java.lang.String transactionID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse partialRefund(java.lang.String merchantID, java.lang.String transactionID, java.math.BigDecimal refundAmount) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse _void(java.lang.String merchantID, java.lang.String transactionID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse capture(java.lang.String merchantID, java.lang.String transactionID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse preauthorizeCreditCard(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse preauthorizeCreditCard2(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse preauthorizeAVS(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse preauthorizeInitialRecur(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse preauthorizeThreeDMPI(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference, java.lang.String ECI, java.lang.String XID, java.lang.String acsVerificationID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeCreditCard(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeAVS(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeInitialRecur(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeThreeDMPI(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference, java.lang.String ECI, java.lang.String XID, java.lang.String acsVerificationID) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeCreditCard2(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String zipCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;

    /**
     * Returns the transaction status for the last MerchantReference
     */
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse checkTransaction(java.lang.String merchantID, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ThreeDVerifyResponse verifyThreeDEnrollment(java.lang.String merchantID, java.lang.String siteID, java.lang.String IPAddress, double amount, java.lang.String currencyID, java.lang.String firstName, java.lang.String lastName, java.lang.String phone, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String postalCode, java.lang.String email, java.lang.String cardNumber, java.lang.String cardName, int expiryMonth, int expiryYear, java.lang.String cardCVV, java.lang.String merchantReference) throws java.rmi.RemoteException;
    public com.payment.alliedwalled.core.message.com._381808.service.ExecuteResponse executeThreeD(java.lang.String merchantID, java.lang.String siteID, java.lang.String MD, java.lang.String paReq) throws java.rmi.RemoteException;
}
