/**
 * ServiceSkeleton.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis2 version: 1.7.3  Built on : May 30, 2016 (04:08:57 BST)
 */
package com.payment.globalgate.www;

/**
 *  ServiceSkeleton java skeleton for the axisService
 */
public class ServiceSkeleton {
    /**
     * Auto generated method signature
     *
     * @param s3DProcess
     * @return s3DProcessResponse
     */
    /*public com.payment.apco.www.S3DProcessResponseDocument s3DProcess(
            com.payment.apco.www.S3DProcessDocument s3DProcess) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#s3DProcess");
    }*/

    /**
     * Auto generated method signature
     * Get transactions which are not generated by AM Portal
     * @param getNextAMTransactions
     * @return getNextAMTransactionsResponse
     */
    /*public biz.apsp.www.GetNextAMTransactionsResponseDocument getNextAMTransactions(
        biz.apsp.www.GetNextAMTransactionsDocument getNextAMTransactions) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getNextAMTransactions");
    }*/

    /**
     * Auto generated method signature
     * Retrieve VbV Signature
     * @param getVbVSignature
     * @return getVbVSignatureResponse
     */
    /*public biz.apsp.www.GetVbVSignatureResponseDocument getVbVSignature(
        biz.apsp.www.GetVbVSignatureDocument getVbVSignature) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getVbVSignature");
    }*/

    /**
     * Auto generated method signature
     * 3D Secure Card Check
     * @param do3DSTransaction
     * @return do3DSTransactionResponse
     */
    /*public com.payment.apco.www.Do3DSTransactionResponseDocument do3DSTransaction(
            com.payment.apco.www.Do3DSTransactionDocument do3DSTransaction) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#do3DSTransaction");
    }

    *//**
     * Auto generated method signature
     * BatchText Download Service
     * @param getBatchFile
     * @return getBatchFileResponse
     *//*
    public biz.apsp.www.GetBatchFileResponseDocument getBatchFile(
        biz.apsp.www.GetBatchFileDocument getBatchFile) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getBatchFile");
    }*/

    /**
     * Auto generated method signature
     * Verify SVP
     * @param verifySVP
     * @return verifySVPResponse
     */
    /*public biz.apsp.www.VerifySVPResponseDocument verifySVP(
        biz.apsp.www.VerifySVPDocument verifySVP) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#verifySVP");
    }*/

    /**
     * Auto generated method signature
     *
     * @param bypassAcquirerProcessing
     * @return bypassAcquirerProcessingResponse
     */
   /* public biz.apsp.www.BypassAcquirerProcessingResponseDocument bypassAcquirerProcessing(
        biz.apsp.www.BypassAcquirerProcessingDocument bypassAcquirerProcessing) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#bypassAcquirerProcessing");
    }*/

    /**
     * Auto generated method signature
     * Batch Text Upload Service
     * @param setBatchFile
     * @return setBatchFileResponse
     */
    /*public biz.apsp.www.SetBatchFileResponseDocument setBatchFile(
        biz.apsp.www.SetBatchFileDocument setBatchFile) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#setBatchFile");
    }

    *//**
     * Auto generated method signature
     * Get Transaction Status
     * @param getTransactionStatus
     * @return getTransactionStatusResponse
     *//*
    public biz.apsp.www.GetTransactionStatusResponseDocument getTransactionStatus(
        biz.apsp.www.GetTransactionStatusDocument getTransactionStatus) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getTransactionStatus");
    }*/

    /**
     * Auto generated method signature
     * Verify SVP
     * @param setOnHold
     * @return setOnHoldResponse
     */
   /* public biz.apsp.www.SetOnHoldResponseDocument setOnHold(
        biz.apsp.www.SetOnHoldDocument setOnHold) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#setOnHold");
    }*/

    /**
     * Auto generated method signature
     * Set Checkout Page Read Receipt
     * @param checkoutReadReceipt
     * @return checkoutReadReceiptResponse
     */
   /* public biz.apsp.www.CheckoutReadReceiptResponseDocument checkoutReadReceipt(
        biz.apsp.www.CheckoutReadReceiptDocument checkoutReadReceipt) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#checkoutReadReceipt");
    }*/

    /**
     * Auto generated method signature
     * Get Merchant Currencies, Acquirers &amp; Cards
     * @param getMerchantInfo
     * @return getMerchantInfoResponse
     */
    /*public biz.apsp.www.GetMerchantInfoResponseDocument getMerchantInfo(
        biz.apsp.www.GetMerchantInfoDocument getMerchantInfo) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getMerchantInfo");
    }

    *//**
     * Auto generated method signature
     * Process PSP Transaction
     * @param doTransaction
     * @return doTransactionResponse
     */
    public DoTransactionResponseDocument doTransaction(
            DoTransactionDocument doTransaction) {
        //TODO : fill this with the necessary business logic
        throw new UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#doTransaction");
    }

    /**
     * Auto generated method signature
     *
     * @param processBankPMTransaction
     * @return processBankPMTransactionResponse
     */
    /*public biz.apsp.www.ProcessBankPMTransactionResponseDocument processBankPMTransaction(
        biz.apsp.www.ProcessBankPMTransactionDocument processBankPMTransaction) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#processBankPMTransaction");
    }*/

    /**
     * Auto generated method signature
     * Check if card needs to be verified by SVP
     * @param isCardPendingSVPVerification
     * @return isCardPendingSVPVerificationResponse
     */
   /* public biz.apsp.www.IsCardPendingSVPVerificationResponseDocument isCardPendingSVPVerification(
        biz.apsp.www.IsCardPendingSVPVerificationDocument isCardPendingSVPVerification) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#isCardPendingSVPVerification");
    }*/

    /**
     * Auto generated method signature
     * Get 3DSecure Transaction Status
     * @param get3DSTransactionStatus
     * @return get3DSTransactionStatusResponse
     */
    /*public biz.apsp.www.Get3DSTransactionStatusResponseDocument get3DSTransactionStatus(
        biz.apsp.www.Get3DSTransactionStatusDocument get3DSTransactionStatus) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#get3DSTransactionStatus");
    }*/

    /**
     * Auto generated method signature
     * Gets Transaction Dynamic Descriptor
     * @param getDDR
     * @return getDDRResponse
     */
    /*public biz.apsp.www.GetDDRResponseDocument getDDR(
        biz.apsp.www.GetDDRDocument getDDR) {
        //TODO : fill this with the necessary business logic
        throw new java.lang.UnsupportedOperationException("Please implement " +
            this.getClass().getName() + "#getDDR");
    }*/
}
