package com.payment.emexpay;

import java.util.HashMap;

/**
 * Created by Uday on 3/5/18.
 */
public class EmexPayErrorCode
{
   private static HashMap<String,String> errorCodes=new HashMap<>();

    static {
        errorCodes.put("000", "Transaction Successful");
        errorCodes.put("001", "Pending for Authorisation");
        errorCodes.put("002", "Awaiting Response From Bank");
        errorCodes.put("101", "-Field is blank in a request");
        errorCodes.put("102", "Internal Mapping for ISO not set");
        errorCodes.put("103", "ISO message field configuration not found");
        errorCodes.put("104", "Response Code not found in ISO message");
        errorCodes.put("105", "Problem while creating or parsing ISO Message");
        errorCodes.put("201", "Terminal does not exists");
        errorCodes.put("202", "Merchant does not exists");
        errorCodes.put("203", "Institution does not exists");
        errorCodes.put("204", "Card prefix is not belong to corresponding card Type");
        errorCodes.put("205", "Card not allowed for this transaction");
        errorCodes.put("206", "Negative IP, Customer is not allowed to perform Transaction");
        errorCodes.put("207", "Original Transaction not found");
        errorCodes.put("208", "Transaction Flow not set for Transaction Type");
        errorCodes.put("209", "Terminal status is Deactive, Transaction Declined");
        errorCodes.put("210", "Terminal status is Closed, Transaction Declined");
        errorCodes.put("211", "Terminal status is Invalid, Transaction Declined");
        errorCodes.put("212", "Merchant status is Deactive, Transaction Declined");
        errorCodes.put("213", "Merchant status is Closed, Transaction Declined");
        errorCodes.put("214", "Merchant status is Invalid, Transaction Declined");
        errorCodes.put("215", "Institution status is Deactive, Transaction Declined");
        errorCodes.put("216", "Institution status is Closed, Transaction Declined");
        errorCodes.put("217", "Institution status is Invalid, Transaction Declined");
        errorCodes.put("218", "MOD10 Check Failed");
        errorCodes.put("219", "Card Type not supported by Merchant");
        errorCodes.put("220", "CVV Check Failed, CVV value not present");
        errorCodes.put("221", "AVS Capture Check Failed, Could not find Customer Address");
        errorCodes.put("222", "Customer Info Check failed, Could not find Customer Information");
        errorCodes.put("223", "Card expiry date is not greater than current date");
        errorCodes.put("224", "Invalid Login Attempts exceeded");
        errorCodes.put("225", "Wrong Terminal password, Please Re-Initiate transaction");
        errorCodes.put("226", "Negative Country, Customer is not allowed to perform Transaction");
        errorCodes.put("227", "Card type not supported by institution");
        errorCodes.put("228", "Multiple captures not allowed");
        errorCodes.put("229", "Amount is invalid");
        errorCodes.put("230", "Inputted value should be numeric");
        errorCodes.put("231", "Inputted value should be alphabetic");
        errorCodes.put("232", "Action code is invalid");
        errorCodes.put("233", "Credit card length is invalid");
        errorCodes.put("234", "Invalid Month");
        errorCodes.put("235", "Mandatory input parameter missing");
        errorCodes.put("236", "Input parameter missing for Purchase");
        errorCodes.put("237", "Input parameter missing for Pre Authorization");
        errorCodes.put("238", "Invalid Customer Name");
        errorCodes.put("239", "Merchant Track Id invalid");
        errorCodes.put("240", "Email address invalid");
        errorCodes.put("241", "Country code invalid");
        errorCodes.put("242", "Cannot exceed original transaction amount");
        errorCodes.put("243", "Mandatory parameter missing. Please check if email is provided");
        errorCodes.put("244", "Mandatory parameter missing. Please check if transid is provided");
        errorCodes.put("245", "Please remove special characters. Please refer to Merchant Integration Document");
        errorCodes.put("246", "Specific operation for transaction is not permitted");
        errorCodes.put("247", "Please configure terminal for an active destination");
        errorCodes.put("248", "Partial Refund not allowed on this terminal");
        errorCodes.put("249", "Invalid hash");
        errorCodes.put("250", "Currency invalid");
        errorCodes.put("301", "Transaction is not allowed for given Terminal");
        errorCodes.put("302", "Transaction is not allowed for given Merchant");
        errorCodes.put("303", "Transaction is not allowed for given Institution");
        errorCodes.put("304", "Currency not supported for given Terminal");
        errorCodes.put("305", "Currency not supported for given Merchant");
        errorCodes.put("306", "Currency not supported for given Institution");
        errorCodes.put("307", "Velocity Check Failed, Velocity Profile not found, Level - Terminal");
        errorCodes.put("308", "Velocity Check Failed, Velocity Profile not found, Level - Merchant");
        errorCodes.put("309", "Velocity Check Failed, Velocity Profile not found, Level - Institution");
        errorCodes.put("310", "Transaction Profile not set for Terminal, Unable to check Transaction Profile");
        errorCodes.put("311", "Transaction Profile not set for Merchant, Unable to check Transaction Profile");
        errorCodes.put("312", "Transaction Profile not set for Institution, Unable to check Transaction Profile");
        errorCodes.put("313", "Currency Profile not set for Terminal, Unable to check Currency Profile");
        errorCodes.put("314", "Currency Profile not set for Merchant, Unable to check Currency Profile");
        errorCodes.put("315", "Currency Profile not set for Institution, Unable to check Currency Profile");
        errorCodes.put("316", "Velocity Profile not set for Terminal, Unable to check Velocity Profile");
        errorCodes.put("317", "Velocity Profile not set for Merchant, Unable to check Velocity Profile");
        errorCodes.put("318", "Velocity Profile not set for Institution, Unable to check Velocity Profile");
        errorCodes.put("319", "Refund Limit exceeds for Terminal");
        errorCodes.put("320", "Refund Limit exceeds for Merchant");
        errorCodes.put("321", "Refund Limit exceeds for Institution");
        errorCodes.put("322", "Velocity Check Failed, Transaction amount below Minimum amount allowed, Level - Terminal");
        errorCodes.put("323", "Velocity Check Failed, Transaction amount below Minimum amount allowed, Level - Merchant");
        errorCodes.put("324", "Velocity Check Failed, Transaction amount below Minimum amount allowed, Level - Institution");
        errorCodes.put("325", "Velocity Check Failed, Transaction amount exceeds Maximum amount allowed, Level - Terminal");
        errorCodes.put("326", "Velocity Check Failed, Transaction amount exceeds Maximum amount allowed, Level - Merchant");
        errorCodes.put("327", "Velocity Check Failed, Transaction amount exceeds Maximum amount allowed, Level - Institution");
        errorCodes.put("328", "Velocity Check Failed, Level - Terminal");
        errorCodes.put("329", "Velocity Check Failed, Level - Merchant");
        errorCodes.put("330", "Velocity Check Failed, Level - Institution");
        errorCodes.put("331", "Velocity Check Failed, Transaction exceeds Total transaction count, Level - Terminal");
        errorCodes.put("332", "Velocity Check Failed, Transaction exceeds Total transaction count, Level - Merchant");
        errorCodes.put("333", "Velocity Check Failed, Transaction exceeds Total transaction count, Level - Institution");
        errorCodes.put("334", "Velocity Check Failed, Transaction amount exceeds Total transaction amount allowed, Level - Terminal");
        errorCodes.put("335", "Velocity Check Failed, Transaction amount exceeds Total transaction amount allowed, Level - Merchant");
        errorCodes.put("336", "Velocity Check Failed, Transaction amount exceeds Total transaction amount allowed, Level - Institution");
        errorCodes.put("337", "Velocity Check Failed, Transaction exceeds Total transaction count of this Card, Level - Terminal");
        errorCodes.put("338", "Velocity Check Failed, Transaction exceeds Total transaction count of this Card, Level - Merchant");
        errorCodes.put("339", "Velocity Check Failed, Transaction exceeds Total transaction count of this Card, Level - Institution");
        errorCodes.put("401", "Destination is not configured");
        errorCodes.put("402", "Can not lookup Destination to send message");
        errorCodes.put("403", "Unable to route Message to Destination");
        errorCodes.put("404", "Unable to get routing details");
        errorCodes.put("405", "Destination does Not Logged on");
        errorCodes.put("501", "Refer to card issuer");
        errorCodes.put("502", "Refer to card issuer, special condition");
        errorCodes.put("503", "Invalid Merchant or Service Provider");
        errorCodes.put("504", "Pick-up card");
        errorCodes.put("505", "Do not honour");
        errorCodes.put("506", "Error");
        errorCodes.put("507", "Pick-up card, special condition");
        errorCodes.put("508", "Honour with identification");
        errorCodes.put("509", "Request in progress");
        errorCodes.put("510", "Approved, partial");
        errorCodes.put("511", "Approved, VIP");
        errorCodes.put("512", "Invalid transaction");
        errorCodes.put("513", "Invalid amount");
        errorCodes.put("514", "Invalid card number");
        errorCodes.put("515", "No such issuer");
        errorCodes.put("516", "Approved, update track 3");
        errorCodes.put("517", "Operator Cancelled");
        errorCodes.put("518", "Customer dispute");
        errorCodes.put("519", "Re enter transaction");
        errorCodes.put("520", "Invalid response");
        errorCodes.put("521", "No action taken");
        errorCodes.put("522", "Suspected malfunction");
        errorCodes.put("523", "Unacceptable transaction fee");
        errorCodes.put("524", "File update not supported");
        errorCodes.put("525", "Unable to locate record");
        errorCodes.put("526", "Duplicate record");
        errorCodes.put("527", "File update edit error");
        errorCodes.put("528", "File update file locked");
        errorCodes.put("529", "Format error");
        errorCodes.put("530", "File update failed");
        errorCodes.put("531", "Bank not supported");
        errorCodes.put("532", "Completed partially");
        errorCodes.put("533", "Expired card, pick-up");
        errorCodes.put("534", "Suspected fraud, pick-up");
        errorCodes.put("535", "Contact acquirer, pick-up");
        errorCodes.put("536", "Restricted card, pick-up");
        errorCodes.put("537", "Call acquirer security, pick-up");
        errorCodes.put("538", "PIN tries exceeded, pick-up");
        errorCodes.put("539", "No credit account");
        errorCodes.put("540", "Function not supported");
        errorCodes.put("541", "Lost card (Contact Bank)");
        errorCodes.put("542", "No universal account");
        errorCodes.put("543", "Stolen card");
        errorCodes.put("544", "No investment account");
        errorCodes.put("551", "Not sufficient funds (Client to Contact Bank)");
        errorCodes.put("552", "No check account");
        errorCodes.put("553", "No savings account");
        errorCodes.put("554", "Expired card (Contact Bank)");
        errorCodes.put("555", "Incorrect PIN");
        errorCodes.put("556", "No card record");
        errorCodes.put("557", "Transaction not permitted to cardholder");
        errorCodes.put("558", "Transaction not permitted on terminal");
        errorCodes.put("559", "Suspected fraud");
        errorCodes.put("560", "Contact acquirer");
        errorCodes.put("561", "Exceeds withdrawal limit");
        errorCodes.put("562", "Restricted card");
        errorCodes.put("563", "Security violation");
        errorCodes.put("564", "Original amount incorrect");
        errorCodes.put("565", "Exceeds withdrawal frequency");
        errorCodes.put("566", "Call acquirer security");
        errorCodes.put("567", "Hard capture");
        errorCodes.put("568", "Response received too late");
        errorCodes.put("575", "PIN tries exceeded");
        errorCodes.put("576", "Approved country club");
        errorCodes.put("577", "Intervene, bank approval required");
        errorCodes.put("578", "Original transaction could not be found");
        errorCodes.put("579", "approved administrative transaction");
        errorCodes.put("580", "Approved national negative file hit OK");
        errorCodes.put("581", "Approved commercial");
        errorCodes.put("582", "No security module");
        errorCodes.put("583", "No accounts");
        errorCodes.put("584", "No PBF");
        errorCodes.put("585", "PBF update error");
        errorCodes.put("586", "Invalid authorisation type");
        errorCodes.put("587", "Bad Track 2 bank offline");
        errorCodes.put("588", "PTLF error");
        errorCodes.put("589", "Invalid route service");
        errorCodes.put("590", "Cut-off in progress");
        errorCodes.put("591", "Issuer or switch inoperative");
        errorCodes.put("592", "Routing error");
        errorCodes.put("593", "Violation of law");
        errorCodes.put("594", "Duplicate transaction");
        errorCodes.put("595", "Reconcile error");
        errorCodes.put("596", "Communication System malfunction");
        errorCodes.put("597", "Communication Error");
        errorCodes.put("598", "Exceeds cash limit");
        errorCodes.put("599", "Host Response,Please check bank response code");
        errorCodes.put("5A0", "Transaction Blocked");
        errorCodes.put("5A1", "Transaction Cancelled");
        errorCodes.put("5A2", "Deffered Transaction");
        errorCodes.put("5A3", "3D Secure Authentication Failed");
        errorCodes.put("5A4", "Card Security Code Failed");
        errorCodes.put("5A5", "Shopping Transaction Locked");
        errorCodes.put("5A6", "Cardholder is not enrolled in 3D Secure");
        errorCodes.put("5A7", "Transaction is Pending");
        errorCodes.put("5A8", "Retry Limits Exceeded, Transaction Not Processed");
        errorCodes.put("5A9", "Address Verification Failed");
        errorCodes.put("5B0", "Card Security Code Failed");
        errorCodes.put("5B1", "Address Verification and Card Security Code Failed");
        errorCodes.put("5B2", "Transaction could not be processed");
        errorCodes.put("5B3", "Transaction Declined - Contact Issuing Bank");
        errorCodes.put("5B4", "Transaction Declined- No reply from Bank");
        errorCodes.put("5B5", "Transaction Declined - Expired Card");
        errorCodes.put("5B6", "Transaction Declined - Insufficient credit");
        errorCodes.put("5B7", "Transaction Declined - Bank system error");
        errorCodes.put("5B8", "Payment Server Processing Error - Typically caused by invalid input data");
        errorCodes.put("5B9", "Transaction Declined - Transaction Type Not Supported");
        errorCodes.put("5C1", "Bank Declined Transaction.Do not contact Bank");
        errorCodes.put("5C2", "Invalid phone number");
        errorCodes.put("5C3", "Missing field");
        errorCodes.put("5C4", "Merchant verification failed, wrong credentials");
        errorCodes.put("5C5", "Card is blocked");
        errorCodes.put("5C6", "Email is blocked");
        errorCodes.put("5C7", "Fraud Screening (FS) not allowed");
        errorCodes.put("5C8", "BIN not found");
        errorCodes.put("5C9", "Card holder full address must be provided in order to perform AVS check with the selected policy");
        errorCodes.put("5D0", "3D verification required");
        errorCodes.put("5D1", "Bad card details");
        errorCodes.put("5D2", "Bad card Holder Country Code");
        errorCodes.put("5D3", "Merchant IP verification failed");
        errorCodes.put("5D4", "Bad currency or card type");
        errorCodes.put("5D5", "Transaction rejected attempting to cancel an captured AUTH transaction");
        errorCodes.put("5D6", "Transaction declined bad credit or reversal on non-captured transaction");
        errorCodes.put("5D7", "Password Must Be Changed");
        errorCodes.put("5D8", "Unknown User");
        errorCodes.put("5D9", "Invalid Token");
        errorCodes.put("5N0", "Unable to authorise / Card type incorrect");
        errorCodes.put("5N1", "Invalid PAN length");
        errorCodes.put("5N2", "Preauthorisation full");
        errorCodes.put("5N3", "Maximum online refund reached");
        errorCodes.put("5N4", "Maximum off-line refund reached");
        errorCodes.put("5N5", "Maximum credit per refund");
        errorCodes.put("5N6", "Maximum refund credit reached");
        errorCodes.put("5N7", "Decline for cvv2 failure");
        errorCodes.put("5N8", "Over floor limit");
        errorCodes.put("5N9", "Maximum number refund credits");
        errorCodes.put("5O0", "Referral file full");
        errorCodes.put("5O1", "NEG file problem");
        errorCodes.put("5O2", "Advance less than minimum");
        errorCodes.put("5O3", "Delinquent");
        errorCodes.put("5O4", "Over limit table");
        errorCodes.put("5O5", "PIN required");
        errorCodes.put("5O6", "Mod 10 check");
        errorCodes.put("5O7", "Force post");
        errorCodes.put("5O8", "Bad PBF");
        errorCodes.put("5O9", "NEG file problem");
        errorCodes.put("5P0", "CAF problem");
        errorCodes.put("5P1", "Over daily limit");
        errorCodes.put("5P2", "CAPF not found");
        errorCodes.put("5P3", "Advance less than minimum");
        errorCodes.put("5P4", "Number of times used");
        errorCodes.put("5P5", "Delinquent");
        errorCodes.put("5P6", "Over limit table");
        errorCodes.put("5P7", "Advance less than minimum");
        errorCodes.put("5P8", "Administrative card needed");
        errorCodes.put("5P9", "Enter lesser amount");
        errorCodes.put("5Q0", "Invalid transaction date");
        errorCodes.put("5Q1", "Invalid expiration date");
        errorCodes.put("5Q2", "Invalid transaction code");
        errorCodes.put("5Q3", "Advance less than minimum");
        errorCodes.put("5Q4", "Number of times used");
        errorCodes.put("5Q5", "Delinquent");
        errorCodes.put("5Q6", "Over limit table");
        errorCodes.put("5Q7", "Amount over maximum");
        errorCodes.put("5Q8", "Administrative card not found");
        errorCodes.put("5Q9", "Administrative card not allowed");
        errorCodes.put("5R0", "Approved administrative request");
        errorCodes.put("5R1", "Approved administrative request");
        errorCodes.put("5R2", "Approved administrative request");
        errorCodes.put("5R3", "Chargeback-customer file updated");
        errorCodes.put("5R4", "Chargeback-customer file updated -acquirer not found");
        errorCodes.put("5R5", "Chargeback-incorrect prefix number");
        errorCodes.put("5R6", "Chargeback-incorrect response code or CPF configuration");
        errorCodes.put("5R7", "Administrative transactions not supported");
        errorCodes.put("5R8", "Card on national negative file");
        errorCodes.put("5S4", "PTLF full");
        errorCodes.put("5S5", "Chargeback-approved, customer file not updated");
        errorCodes.put("5S6", "Chargeback-approved, customer file not updated, acquirer not found");
        errorCodes.put("5S7", "Chargeback-accepted, incorrect destination");
        errorCodes.put("5S8", "ADMN file problem");
        errorCodes.put("5S9", "Unable to validate PI");
        errorCodes.put("5T1", "Invalid credit card advance amount");
        errorCodes.put("5T2", "Invalid transaction date");
        errorCodes.put("5T3", "Card not supported");
        errorCodes.put("5T4", "Amount over maximum");
        errorCodes.put("5T5", "CAF status = 0 or 9");
        errorCodes.put("5T6", "Bad UAF");
        errorCodes.put("5T7", "Cash back exceeds daily limit");
        errorCodes.put("5T8", "Multiple invalid required fields");
        errorCodes.put("5T9", "Authorize transaction has not been progressed at bank side");
        errorCodes.put("5U0", "Bank Declined Transaction");
        errorCodes.put("5U1", "No Reply from Bank");
        errorCodes.put("5U2", "Expired Card");
        errorCodes.put("5U3", "Insufficient Funds");
        errorCodes.put("5U4", "Error Communicating with Bank");
        errorCodes.put("5U5", "Payment Server System Error");
        errorCodes.put("5U6", "Transaction Type Not Supported");
        errorCodes.put("5U7", "Bank declined transaction (Do not contact Bank)");
        errorCodes.put("5U8", "Transaction Aborted");
        errorCodes.put("5U9", "Transaction Cancelled");
        errorCodes.put("5V0", "Deferred transaction has been received and is awaiting processing");
        errorCodes.put("5V2", "Card Security Code verification failed");
        errorCodes.put("5V3", "Shopping Transaction Locked (Please try the transaction again later)");
        errorCodes.put("5V4", "Cardholder is not enrolled in Authentication Scheme");
        errorCodes.put("5V5", "Transaction has been received by the Payment Adaptor and is being processed");
        errorCodes.put("5V6", "Transaction was not processed - Reached limit of retry attempts allowed");
        errorCodes.put("5V7", "Duplicate SessionID (OrderInfo)");
        errorCodes.put("5V8", "Address Verification Failed");
        errorCodes.put("5V9", "Card Security Code Failed");
        errorCodes.put("5W0", "Address Verification and Card Security Code Failed");
        errorCodes.put("5W1", "Transaction status is unknown");
        errorCodes.put("5W2", "Bad currency or card type");
        errorCodes.put("5W3", "Only full 3D Secure authentication allowed");
        errorCodes.put("601", "System Error, Please contact System Admin.");
        errorCodes.put("602", "System Error,Please try again");
        errorCodes.put("603", "Transaction timed out.");
        errorCodes.put("604", "Invalid Card Number.");
        errorCodes.put("605", "Invalid CVV.");
        errorCodes.put("606", "Invalid Track Id.");
        errorCodes.put("607", "Invalid Terminal Id.");
        errorCodes.put("608", "Invalid Address.");
        errorCodes.put("609", "Invalid Terminal Password.");
        errorCodes.put("610", "Invalid Action Code.");
        errorCodes.put("611", "Invalid Currency Code.");
        errorCodes.put("612", "Invalid Transaction Amount.");
        errorCodes.put("613", "Invalid Transaction Reference.");
        errorCodes.put("614", "Invalid UserFields.");
        errorCodes.put("615", "Invalid City.");
        errorCodes.put("616", "Invalid characters encountered.");
        errorCodes.put("617", "Invalid Card Expiry Date.");
        errorCodes.put("618", "Invalid State");
        errorCodes.put("619", "Invalid Country");
        errorCodes.put("620", "Invalid Cardholder Name.");
        errorCodes.put("621", "Invaild ZipCode.");
        errorCodes.put("622", "Invalid IP Address.");
        errorCodes.put("623", "Invalid Email Address.");
        errorCodes.put("624", "Transaction cancelled by the user.");
        errorCodes.put("625", "3D Secure Check Failed, Cannot continue transaction");
        errorCodes.put("626", "Invalid CVV,CVV Mandatory.");
        errorCodes.put("627", "Capture not allowed, Mismatch in Capture and Original Auth Transaction Amount.");
        errorCodes.put("628", "Transaction has not been Captured/Purchase, Refund not allowed.");
        errorCodes.put("629", "Refund Amount exceeds the Captured/Purchase Amount.");
        errorCodes.put("630", "Transaction is Void, Capture not allowed.");
        errorCodes.put("631", "Transaction has been Captured, Void Auth not allowed.");
        errorCodes.put("632", "Original Transaction not found.");
        errorCodes.put("633", "Transaction already Refunded, Duplicate refund not allowed.");
        errorCodes.put("634", "Transaction is Void, Refund not allowed.");
        errorCodes.put("635", "Transaction has been Captured, Multiple captures not allowed.");
        errorCodes.put("636", "Transaction has been Voided , Multiple voids not allowed.");
        errorCodes.put("637", "A purchase transaction cannot be captured. It should be an Auth transaction.");
        errorCodes.put("638", "Purchase transaction cannot be Voided.");
        errorCodes.put("639", "Invalid Void Transaction, Void and Original Auth Transaction Amount mismatched.");
        errorCodes.put("640", "Refund transaction in progress, Cannot process duplicate transaction");
        errorCodes.put("641", "Capture transaction in progress, Cannot process duplicate transaction");
        errorCodes.put("642", "Void Auth transaction in progress, cannot process duplicate transaction");
        errorCodes.put("644", "Transaction is fully refunded, refund not allowed");
        errorCodes.put("645", "Transaction is chargeback transaction, refund not allowed");
        errorCodes.put("646", "Transaction is chargeback transaction, refund amount exceeds allowed amount");
        errorCodes.put("647", "Invalid subscription type");
        errorCodes.put("648", "Invalid payment type");
        errorCodes.put("649", "Invalid payment cycle");
        errorCodes.put("650", "Invalid payment start date");
        errorCodes.put("651", "Invalid payment days");
        errorCodes.put("652", "Invalid payment Method");
        errorCodes.put("653", "Terminal not allow for recurring payment");
        errorCodes.put("654", "Invalid Recurring Amount");
        errorCodes.put("655", "Invalid payment type");
        errorCodes.put("656", "Invalid No of recurring payment");
        errorCodes.put("657", "Recurring cycle limit exceeds, cannot set recurring for more than 2 years");
        errorCodes.put("658", "Amount 0.00 is not supported for Pre-auth transaction");
        errorCodes.put("659", "Amount to be voided exceeds Pre-Auth amount after capture");
        errorCodes.put("660", "Partial Void Not Allowed");
        errorCodes.put("661", "Mandatory inputs for recurring transactions are missing");
        errorCodes.put("662", "PaymentDays input tag is missing");
        errorCodes.put("663", "NoOfRecurringPayments input tag is missing");
        errorCodes.put("670", "Communication error while writing in Socket");
        errorCodes.put("671", "Communication error while reading in Socket");
        errorCodes.put("699", "Transaction timed out from bank");
        errorCodes.put("700", "Delayed transaction awaiting response from bank");
        errorCodes.put("799", "TM Timeout");

    }

    public static String getDescription(String code){
        String description=errorCodes.get(code);
        return description;
    }

}
